version: '3.8'

services:
  db:
    image: postgres:16.4
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  core:
    build: .
    command: bash -c "python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/opt/task_manager
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: always

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  db_vol:
